project: hubmap

hydra:
  run:
    dir: ./runs/${model.arch}-${model.encoder_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

seed: 56
device: 0

data:
  path: data/hubmap-256x256/
  train_ids: [0, 1, 2, 3, 4, 5, 6]
  valid_ids: [7]  # Should always be a list
  valid_split: 0.1  # Use when valid_ids is empty
#  mean: [0.65459856, 0.48386562, 0.69428385]  # HuBMAP
#  std: [0.15167958, 0.23584107, 0.13146145]
  mean: [0.485, 0.456, 0.406]  # Imagenet
  std: [0.229, 0.224, 0.225]

loader:
  train_bs: 16
  valid_bs: 16
  num_workers: 4

model:
  arch: unet
  encoder_name: se_resnext50_32x4d
  encoder_weights: imagenet
  convert_bn: False

optim:
  name: radam
  lookahead: true
  lr: 1e-3
  wd: 0
  lr_encoder: 1e-3
  wd_encoder: 0

loss:
  bce: 1.0
  dice: 1.0
  iou: 0
  lovasz: 0

scheduler:
  type: cosine
  plateau:
    patience: 10
    factor: 0.1
  early_stopping:
    patience: 20
    metric: dice


train:
  logdir: catalyst_log
  num_epochs: 60
  main_metric: dice


