project: hubmap

hydra:
  run:
    dir: ./runs/${model.arch}-${model.encoder_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

seed: 56
device: 0

data:
  path: data/hubmap-256x256/
  train_ids: [0, 1, 2, 3, 4, 5, 6]
  valid_ids: [7]
  mean: [0.65459856, 0.48386562, 0.69428385]
  std: [0.15167958, 0.23584107, 0.13146145]

loader:
  train_bs: 12
  valid_bs: 16
  num_workers: 4

model:
  arch: unetplusplus
  encoder_name: densenet169
  encoder_weights: imagenet

optim:
  name: radam
  lookahead: true
  lr: 1e-3
  wd: 3e-4
  lr_encoder: 5e-4
  wd_encoder: 3e-5

scheduler:
  plateau:
    patience: 10
    factor: 0.1
  early_stopping:
    patience: 20
    metric: dice


train:
  logdir: catalyst_log
  num_epochs: 100
  main_metric: dice


